app/models/gallery.py
import os
import shutil
from werkzeug.utils import secure_filename
from app import db
from app import app


class Gallery(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    images = db.relationship('Img', lazy='dynamic', backref=db.backref(
        'parent', remote_side=[id]))

    def main_img(self):
        return self.images.order_by(Img.order).first()

    def ordered_imgs(self):
        return self.images.order_by(Img.order).all()

    def upload_images(self, imgs):
        dir_path = os.path.join(app.config['UPLOAD_FOLDER'], str(self.id))
        if not os.path.isdir(dir_path):
            os.mkdir(dir_path, 0764)

        gallery_imgs = []
        inc = self.images.count()
        for index, img in enumerate(imgs):
            index = index + inc
            name = secure_filename(img.filename)
            gallery_imgs.append(Img(name=name, parent=self, order=index))
            img.save(os.path.join(dir_path,  name))

        db.session.add_all(gallery_imgs)
        db.session.commit()

    def delete_images(self):
        imgs = self.images.all()
        for img in imgs:
            db.session.delete(img)

        dir_path = os.path.join(app.config['UPLOAD_FOLDER'], str(self.id))
        shutil.rmtree(dir_path)

        db.session.commit()


class Img(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    order = db.Column(db.Integer)
    parent_id = db.Column(db.Integer, db.ForeignKey('gallery.id'))

    def url(self):
        return '/galleries/{}/{}'.format(self.parent_id, self.name)

    def remove_file(self):
        file_path = os.path.join(
            app.config['UPLOAD_FOLDER'], str(self.parent_id), self.name)
        os.remove(file_path)

app/controllers/main.py
# coding=utf-8
from flask import redirect
from flask import render_template
from flask import Blueprint
from flask.ext.login import logout_user

blueprint = Blueprint('main', __name__)


@blueprint.route('/')
def index(**kwargs):
    return render_template('index.html')


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect('main.index')


@blueprint.route('/gallery')
def gallery():
    return render_template('gallery.html')

app/templates/base_tmpl.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script src="js/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="js/modernizr.custom.86080.js"></script>
        <script type="text/javascript" src="js/galleriffic/jquery.history.js"></script>
        <script type="text/javascript" src="js/galleriffic/jquery.galleriffic.js"></script>
        <script type="text/javascript" src="js/galleriffic/jquery.opacityrollover.js"></script>
        <script type="text/javascript" src="js/jquery-cookie.js"></script>
        <script type="text/javascript" src="js/jquery.watermark.min.js"></script>
        <script type="text/javascript" src="js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="js/jquery.form.js"></script>
        <link rel="stylesheet" href="css/shopstyle.css" />
        <link rel="stylesheet" type="text/css" href="css/backanim.css" />
        <link rel="shortcut icon" href="img/favicon.ico" type="image/icon">
        <link rel="icon" href="img/favicon.ico" type="image/icon">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" href="css/borders/storeborders.css" />
        <link rel="canonical" href="http://www.asantiforkids.com/" />
        {% block header %}{% endblock %}
    </head>
    <body>
        <div class="bg"></div>
        <ul class="cb-slideshow">
            <li><span>Image 01</span></li>
            <li><span>Image 02</span></li>
            <li><span>Image 03</span></li>
            <li><span>Image 04</span></li>
        </ul>
        <div id="background">
            <div class ="panel-div">
                <div class="sub-panel-div" id="profile" >
                    <p>Witaj.&#160;</p>
                    <a data-ng-href="/login">
                        <p class="p-profile" id="p-login">Zaloguj się</p>
                    </a>
                    <p>&#160;lub&#160;</p>
                    <a data-ng-href="/register">
                        <p class="p-profile" id="p-register">załóż konto.</p>
                    </a>
                </div>
                <div class="sub-panel-div" id="profile-icon" ></div>
            </div>
            <div class="n-menu">
                <a class="n-menu-a" data-ng-href="/contact" class="n-item">Kontakt</a>
                <a class="n-menu-a" href="{{ url_for('main.gallery') }}" class="n-item">Galeria</a>
                <a class="n-menu-a" data-ng-href="/about" class="n-item">O Nas</a>
                <a class="n-menu-a" data-ng-href="/regulations" class="n-item">Regulamin</a>
                <a class="n-menu-a" data-ng-href="/payments" class="n-item">Dostawa i płatności</a>
                <a class="n-menu-a" data-ng-href="/promotions" class="n-item">Promocje</a>
                <a class="n-menu-a" data-ng-href="/" class="n-item">Sklep</a>
            </div>
        </div>

        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <style>@import url("css/borders/footerborders.css");</style>
        <div class="bigdivf">
            <div class="rowdivf" id="topdivf">
            </div>
            <div class="rowdivf" id="middivf">
                <div class="rightdivf" id="midrightdivf">
                </div>
                <div class="centerdivf" id="midcenterdivf">
                    <div id="wrapper">
                        <p><a href = "payments.php" class="n-item">Płatności</a></p>
                        <p><a href = "about.php" class="n-item">O Nas</a></p>
                        <p><a href = "gallery.php" class="n-item">Galeria</a></p>
                        <p><a href = "promo.php" class="n-item">Promocje</a></p>
                        <p><a href = "index.php" class="n-item">Sklep</a></p>
                    </div>
                </div>
                <div class="leftdivf" id="midleftdivf">
                </div>
            </div>
            <div class="rowdivf" id="botdivf">
            </div>
        </div>
    </body>
</html>

app/templates/gallery.html
{% extends "base_tmpl.html" %}

{% block content %}
<div id="gallery">
    <div class="bigdiv">
        <div class="rowdiv" id="topdiv"></div>
        <div class="rowdiv" id="middiv">
            <div class="rightdiv" id="midrightdiv"></div>
            <div class="centerdiv" id="midcenterdiv">
                <div id="title">Nasza Galeria</div>
                <div id="container">
                    <a href="gallery.php?action=show&id=2">
                        <div class="box">
                            <img src="http://serwer1369061.home.pl/img/gallery/2/IMG_7089.jpg" class="boxImg" />
                            <div class="title">Sesja jesienna. Nasi mali modele spisali się wspaniale:)</div>
                        </div>
                    </a>
                    <a href="gallery.php?action=show&id=3">
                        <div class="box">
                            <img src="http://serwer1369061.home.pl/img/gallery/3/IMG_9320.jpg" class="boxImg" />
                            <div class="title">Komplety zwierzaki w nowej odsłonie. Pozowała najsłodsza modelka świata:)</div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="leftdiv" id="midleftdiv"></div>
        </div>
        <div class="rowdiv" id="botdiv"></div>
    </div>
</div>
{% endblock %}